language: cpp
git:
  depth: 3
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - rpm
matrix:
  include:
  - os: linux
    compiler: gcc
    script:
    - cmake . -B Build -DCMAKE_BUILD_TYPE=Release
    - cmake --build Build --config Release --target package
  - os: windows
    language: cpp
    install:
    - choco install nsis 7zip
    script:
    - cmake . -B Build
    - cmake --build Build --config Release --target package
  - os: osx
    osx_image: xcode9.1
    script:
#    - ./build.sh ios -x && cd Build-iOS
#    - |
#      xcrun xcodebuild -quiet -project SpinDrops.xcodeproj -target SpinDrops \
#            CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO
#    - ls
#    - ls Release-iphoneos
    - cmake . -B Build -DCMAKE_BUILD_TYPE=Release
    - cmake --build Build --config Release --target package
before_install:
- |
  if [[ $TRAVIS_OS_NAME == linux && "$CXX" = "g++" ]]; then
      export CXX="g++-8" CC="gcc-8"
  fi
- |
  if [[ $TRAVIS_OS_NAME == linux && "$CXX" = "clang++" ]]; then
      export CXX="clang++-3.7" CC="clang-3.7";
  fi
- cmake --version
script:
- echo script
after_failure:
- pwd
- find .
- cat CMakeFiles/CMakeOutput.log
- ls thirdparty
- cat thirdparty/CMakeFiles/CMakeOutput.log
branches:
  only:
  - /tag.*/
  - master
