language: cpp
git:
  depth: 3
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - rpm
matrix:
  include:
  - os: linux
    compiler: gcc
    script:
    - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release
    - cmake --build build --config Release --target package
  - os: windows
    language: cpp
    install:
    - choco install nsis 7zip
    script:
    - cmake . -Bbuild
    - cmake --build build --config Release --target package
  - os: osx
    osx_image: xcode9.1
    script:
    - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release
    - cmake --build build --config Release --target package
before_install:
- |
  if [[ $TRAVIS_OS_NAME == linux && "$CXX" = "g++" ]]; then
      export CXX="g++-8" CC="gcc-8"
  fi
- |
  if [[ $TRAVIS_OS_NAME == linux && "$CXX" = "clang++" ]]; then
      export CXX="clang++-3.7" CC="clang-3.7";
  fi
- cmake --version
script:
- echo script
after_failure:
- pwd
- find .
- cat CMakeFiles/CMakeOutput.log
- ls thirdparty
- cat thirdparty/CMakeFiles/CMakeOutput.log
branches:
  only:
  - /tag.*/
  - master
deploy:
  provider: releases
  api_key:
    secure: mIq0FS093HbZMDuEh0HunkqIPnMT3ernPo3Iu952VCoPXuKUAlgDaqf6mqxjbLVeA0TpEC+gVNXdn8xM6XTGdZ6CEwysI7dz7/n2XrA05MJ7G5IloyWF7vBefXNChKQajlvtLX6+wo0RtIa/LdCkyF8F291egjgcwsfzDOgCISbTnj0rI6D5m5w//OXV2hu9hWfacUq6oTdVetfH9Bw3NCuUapfst1ykUVq9+qRDAogEakejnlYB9BXZBqgP/fzRxzeL4gN3TdOm1N33JGJQkucVpyezmJMcDKdXM+GnBvp/+v8/F7awnG7yBZYsw6P/MuHlj1D/hq6E2RPVrGBIVQDM2i5E8h6uOa/DJ41NO49pPD/DehAZtUAur0DDOpjMNd22F+8xoP0arbJzU9j8H6ayNtVMsvTv0+JVit/B3b9e8ITy66qeH0LQmbkFgl1SnnyDhM0Z8znmQfpgGL3idTp1jBapvnsDaxcMAmwhLRqILh4ZWKoDGYXe/YpCXuL6sDvxtA/df09iTzG+uEvLrdQTQzBaiMBzRfO6gY2C7zk//GH3glqAvwmtX7Jg9fhQ/w1wil7nm2oF76NAvmKSB6DKjLf5o6NZ5iK1XlMyImfayXh78dBvPIXPDkK+zDBvmLqDHo9dRm3Sfs42t7O5zMGutHyNgzeYmXruG65Q2sY=
  file_glob: true
  file:
    - mypackage*install-win32.exe
    - mypackage*install-win32.zip
    - mypackage*.dmg
    - mypackage*.deb
    - mypackage*.rpm
    - mypackage*.tar.gz
  skip_cleanup: true
  overwrite: true
  draft: true
  name: $TRAVIS_TAG
  on:
    repo: tesch1/SDL2-cmake-example
    tags: true
